/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binus.datastructure.palindrome;

public class App {
    public void run() {
        // Get user input
        String input = System.console().readLine("Enter a string: ");

        // Check if the input is a palindrome
        // First check using the stack ver.
        System.out.println("Using stack ver.:");
        if (Palindrome.checkPalindromeStack(input)) {
            System.out.println(String.format("The string \"%s\" is a palindrome.", input));
        } else {
            System.out.println(String.format("The string \"%s\" is not a palindrome.", input));
        }

        // Then check using the queue ver.
        System.out.println("Using queue ver.:");
        if (Palindrome.checkPalindromeQueue(input)) {
            System.out.println(String.format("The string \"%s\" is a palindrome.", input));
        } else {
            System.out.println(String.format("The string \"%s\" is not a palindrome.", input));
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }
}
