/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binus.datastructure.palindrome;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testCheckPalindrome() {
        Palindrome palindrome = new Palindrome();

        // racecar
        assertTrue(palindrome.checkPalindromeStack("racecar"));
        assertTrue(palindrome.checkPalindromeQueue("racecar"));

        // Borrow or rob
        assertTrue(palindrome.checkPalindromeStack("Borrow or rob"));
        assertTrue(palindrome.checkPalindromeQueue("Borrow or rob"));

        // sedan
        assertFalse(palindrome.checkPalindromeStack("sedan"));
        assertFalse(palindrome.checkPalindromeQueue("sedan"));

        // This is not a palindrome
        assertFalse(palindrome.checkPalindromeStack("This is not a palindrome"));
        assertFalse(palindrome.checkPalindromeQueue("This is not a palindrome"));
    }
}
