/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binus.datastructure.palindrome;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testCheckPalindrome() {
        Palindrome palindrome = new Palindrome();

        // racecar
        assertTrue(palindrome.checkPalindromeStack("racecar"));
        assertTrue(palindrome.checkPalindromeQueue("racecar"));

        // kayak
        assertFalse(palindrome.checkPalindromeStack("sedan"));
        assertFalse(palindrome.checkPalindromeQueue("sedan"));

        // bed
        assertFalse(palindrome.checkPalindromeStack("bed"));
        assertFalse(palindrome.checkPalindromeQueue("bed"));
        
        // Borrow or rob
        assertTrue(palindrome.checkPalindromeStack("Borrow or rob"));
        assertTrue(palindrome.checkPalindromeQueue("Borrow or rob"));
    }
}
